### ISSUE TITLE
chmod

### ISSUE THREAD

**Issue by KommuSoft** [NorfairKing/chronicle#1]
Something that seems to be missing in most journaling systems (_RedNotebook_) is access management: the access rights for the files are set as defaults, so that basically comes down to:

```
-rw-rw-r--
```

Besides using encryption, it is always useful if the operating system aims to prevent a hacker from getting the content anyway, encrypted or not. Thus perhaps an additional option could be to automatically use `chmod`?

**Comment by NorfairKing** [comment]
This sounds like a great idea!
What kind of access control did you have in mind?
Something like this?

```
-rw-------
```
