### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by th0rgall** [NorfairKing/chronicle#2]
- An optional extra argument to title entries might be nice, for example `chronicle enter "example title"` which is then appended to or replacing the generated date filename, depending on configuration.
- A `chronicle edit` and/or `chronicle read` command could be helpful for encrypted entries.

Maybe this is not the right place for suggestions, but it still seems more appropriate than a tweet/pm. Thanks for sharing this!

**Comment by NorfairKing** [comment]
- First suggestion:
  I'm in favor of giving you control over the system but:
  1. It's not secure to leak contents in the filename (this is important if you use encryption).
  2. You would have to sanitise the string to go well with file names and I'm not sure the string would still be useful as content at that point.
  3. You're going to have to type the string anyway so you might as well write it as the first line in your file. (I'm assuming that you'd use it to find entries.)
- Second suggestion:
  Yes please! This sounds very useful. I hadn't really thought the encryption use-case through. Feel free to submit a pull request.

**Comment by th0rgall** [comment]
On the title: you do have a point, indeed it would be to quickly find a specific entry. It's probably not a feature that's worth the work, I would also barely use it, and if needed, manual editing is still possible.

About the encryption use case: some people might only want to encrypt some entries, whilst others would encrypt the whole journal. In the former case it is cumbersome to change the config file each time, in the latter case having to submit a (probably the same) key each time is cumbersome.

To solve the former something like `chronicle enter enc` could be used. For the latter I guess some sort of key saving system is needed.

About that pull request: I know very little Bash programming, I would have to figure it out further which I'll probably do over time this year. I don't want to spoil your script with messy code now.
